Grazing
NGEET/fates pull request #1140
Opened 2023-12-19 16:29 UTC by ckoven

An initial implementation to allow herbivores to graze and browse plants, with different grazing rates on different land use classes.

### Description:
This PR adds the basic capability to have grazers and browsers eat plants. The basic idea is to specify this as a rate of consumption in units of 1/time. I.e. grazers and browsers eat X% of all accessible leaves of edible plants per day on columns of land-use type Y, as controlled by the parameter `fates_landuse_grazing_rate(fates_landuseclass)`. The specification of what is considered edible plants is parametric and controlled by a PFT-level trait `fates_landuse_grazing_palatability(fates_pft)`, so e.g. this can be specified to include grazers (who eat herbaceous plants only) and/or browsers (who eat the leaves of woody plants). And then all leaves of that PFT on columns of that land use type that are below a height of parameter `fates_landuse_grazing_maxheight` can be subject to herbivory.

The fate of the eaten material is controlled by three "use-efficiency" parameters: `fates_landuse_grazing_carbon_use_eff`', `fates_landuse_grazing_nitrogen_use_eff`, 'fates_landuse_grazing_phosphorus_use_eff'. So some mass can be lost from the ecosystem and some can be added to the litter pools via manure (and, I suppose, mortality of grazers).

Default parameter values that are there now (all of which extremely subject to change) are to make this only apply on pasture and rangeland, with a rate of 4% per day based on https://doi.org/10.5194/gmd-11-815-2018 by @samsrabin et al., and currently only grazers (i.e. only applies to nonwoody PFTs). I couldn't find a whole lot of data on the use-efficiency parameters, but those shouldn't be too important until we are running nutrient cycles at large scale under transient change.

fixes https://github.com/NGEET/fates/discussions/936

### Collaborators:

### Expectation of Answer Changes:
This will be answer changing if the parameters are set to allow grazing.

### Checklist

*If this is your first time contributing, please read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/main/CONTRIBUTING.md) document.*

All checklist items must be checked to enable merging this pull request:

*Contributor*
- [x] The in-code documentation has been updated with descriptive comments
- [x] The documentation has been assessed to determine if updates are necessary

*Integrator*
- [ ] FATES PASS/FAIL regression tests were run
- [ ] Evaluation of test results for answer changes was performed and results provided

### Documentation

- [Technical Note](https://github.com/NGEET/fates-docs) update:
- [User's Guide](https://github.com/NGEET/fates-users-guide) update: 

### Test Results:

*CTSM (or) E3SM (specify which) test hash-tag:*

*CTSM (or) E3SM (specify which) baseline hash-tag:*

*FATES baseline hash-tag:*

*Test Output:*

2024-07-05 22:13 UTC, samsrabin reviewed
Not sure if this was actually ready for review, as it has the "draft" tag but isn't a Draft in the Github sense. Anyway, I've made some (initial?) comments. Also: Where are the new parameters actually read?

2024-07-05 22:13 UTC, samsrabin commented on parteh/PRTGenericMod.F90
> +      ! This function is very very similar to GetBurned
In fact it looks identical, aside from `herbivory` replacing `burned`. Could these be replaced with a single function? Named, e.g., `GetDisturbed`.

2024-07-05 22:13 UTC, samsrabin commented on parteh/PRTLossFluxesMod.F90
> +             consumed_mass = mass_fraction * prt%variables(i_var)%val(i_pos)
`consumed_mass` should presumably be `herbivore_consumed_mass`?

2024-07-08 21:29 UTC, ckoven commented
> Not sure if this was actually ready for review, as it has the "draft" tag but isn't a Draft in the Github sense. Anyway, I've made some (initial?) comments. Also: Where are the new parameters actually read?

Thanks @samsrabin! Yes, this is draft in the sense that it wasn't done or tested. And yes, one of the things that isn't done yet is the code to actually read the new parameters. But better to get eyes on it sooner rather than later.

2025-01-11 00:45 UTC, glemieux requested changes
I had some minor suggested name changes and one question.  I'll push an update to add the xml patch file for the cdl update.

2025-01-11 00:45 UTC, glemieux commented on main/EDMainMod.F90
> +             call fates_grazing(currentCohort%prt, ft, currentPatch%land_use_label, currentCohort%height)
```suggestion
             call FatesGrazing(currentCohort%prt, ft, currentPatch%land_use_label, currentCohort%height)
```

2025-01-11 00:45 UTC, glemieux commented on main/FatesHistoryInterfaceMod.F90
> +                  hio_grazing_si(io_si) = hio_grazing_si(io_si) + leaf_herbivory * n_perm2 / days_per_year / sec_per_day
I've never really thought about this: Why do we multiply by `days_per_year` and then divide it out again?

2025-01-21 22:26 UTC, glemieux commented
Preliminary regression testing against `sci.1.80.6_api.37.0.0` baseline shows expected FIELDLIST differences due to the new `FATES_GRAZING` history output not being available in the baselines.  Almost all other tests are B4B, with the exception of the `FatesColdPRT2` test:

```
  525 dec1212.hsn.de.hpc.ucar.edu 622: forrtl: severe (408): fort: (2): Subscript #1 of the array MASS_BALANCE has value 4 which is greater than the upper bound of 3
  526 dec1212.hsn.de.hpc.ucar.edu 622:
  527 dec1212.hsn.de.hpc.ucar.edu 622: Image              PC                Routine            Line        Source
  528 dec1212.hsn.de.hpc.ucar.edu 622: cesm.exe           0000000001D15A0B  edphysiologymod_m        2964  EDPhysiologyMod.F90
  529 dec1212.hsn.de.hpc.ucar.edu 622: cesm.exe           0000000001CD062B  edphysiologymod_m         485  EDPhysiologyMod.F90
  530 dec1212.hsn.de.hpc.ucar.edu 622: cesm.exe           0000000001BFE5BB  edmainmod_mp_ed_i         785  EDMainMod.F90
  531 dec1212.hsn.de.hpc.ucar.edu 622: cesm.exe           0000000001BF7DB2  edmainmod_mp_ed_e         223  EDMainMod.F90
  532 dec1212.hsn.de.hpc.ucar.edu 622: cesm.exe           0000000000B13944  clmfatesinterface        1250  clmfates_interfaceMod.F90
  533 dec1212.hsn.de.hpc.ucar.edu 622: cesm.exe           0000000000A89E08  clm_driver_mp_clm        1143  clm_driver.F90
```

I haven't dug into this yet.  Any initial thoughts @rgknox?

2025-01-22 00:10 UTC, ckoven commented
> Preliminary regression testing against `sci.1.80.6_api.37.0.0-ctsm5.3.018` baseline shows expected FIELDLIST differences due to the new `FATES_GRAZING` history output not being available in the baselines. Almost all other tests are B4B, with the exception of the `FatesColdPRT2` test:
> 
> ```
>   525 dec1212.hsn.de.hpc.ucar.edu 622: forrtl: severe (408): fort: (2): Subscript #1 of the array MASS_BALANCE has value 4 which is greater than the upper bound of 3
>   526 dec1212.hsn.de.hpc.ucar.edu 622:
>   527 dec1212.hsn.de.hpc.ucar.edu 622: Image              PC                Routine            Line        Source
>   528 dec1212.hsn.de.hpc.ucar.edu 622: cesm.exe           0000000001D15A0B  edphysiologymod_m        2964  EDPhysiologyMod.F90
>   529 dec1212.hsn.de.hpc.ucar.edu 622: cesm.exe           0000000001CD062B  edphysiologymod_m         485  EDPhysiologyMod.F90
>   530 dec1212.hsn.de.hpc.ucar.edu 622: cesm.exe           0000000001BFE5BB  edmainmod_mp_ed_i         785  EDMainMod.F90
>   531 dec1212.hsn.de.hpc.ucar.edu 622: cesm.exe           0000000001BF7DB2  edmainmod_mp_ed_e         223  EDMainMod.F90
>   532 dec1212.hsn.de.hpc.ucar.edu 622: cesm.exe           0000000000B13944  clmfatesinterface        1250  clmfates_interfaceMod.F90
>   533 dec1212.hsn.de.hpc.ucar.edu 622: cesm.exe           0000000000A89E08  clm_driver_mp_clm        1143  clm_driver.F90
> ```
> 
> I haven't dug into this yet. Any initial thoughts @rgknox?
> 
> Results: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_pr1140-fates-woodyfix`

I think I see the error that caused this, will fix.

2025-01-24 00:37 UTC, ckoven commented on biogeochem/FatesLandUseChangeMod.F90
> +  subroutine fates_grazing(prt, ft, land_use_label, height)
```suggestion
  subroutine FatesGrazing(prt, ft, land_use_label, height)
```

2025-01-24 00:38 UTC, ckoven commented on biogeochem/FatesLandUseChangeMod.F90
> +  end subroutine fates_grazing
```suggestion
  end subroutine FatesGrazing
```

2025-01-24 00:41 UTC, ckoven commented on main/EDMainMod.F90
> +  use FatesLandUseChangeMod,  only: fates_grazing
```suggestion
  use FatesLandUseChangeMod,  only: FatesGrazing
```

2025-01-25 03:53 UTC, jenniferholm reviewed
Thanks Charlie this is really cool work.  My biggest question was just some confusion around if mass can be loss from the ecosystem via both food/consumption pathway and to the litter flux to the atmosphere, and added to the litter via manure. Are all three pathways occurring, and is the order correct?  Plus does litter from natural litter fluxes plus manure equal the total litter in the history outputs?  I'm not sure that made sense, but wondering if we could separate those out?  Thanks!

2025-01-25 03:53 UTC, jenniferholm commented on biogeochem/EDPhysiologyMod.F90
>      !----------------------------------------------------------------------
Maybe give a short definition of these two? leaf_herbivory and herbivory_element_use_efficiency

2025-01-25 03:53 UTC, jenniferholm commented on biogeochem/EDPhysiologyMod.F90
> +               leaf_herbivory * herbivory_element_use_efficiency) * &
Just to help me understand the steps, will the leaf litter here already take into account the leaf mass that is consumed and "stays" in the animal as food, and only a portion returning to the litter as "manure"?  Is that the herbivory_element_use_efficiency parameter, or something else?  Because I'm also confused about what portion of the litter is food, is manure, and/or to the atmosphere, and if all 3 paths are tracked?

2025-01-25 03:53 UTC, jenniferholm commented on biogeochem/EDPhysiologyMod.F90
> +            leaf_herbivory * (1._r8 - herbivory_element_use_efficiency) * currentCohort%n
Since it looks like 1._r8 - herbivory_element_use_efficiency is the portion that goes to the atmosphere, is the other portion only going to manure, food diet consumption, or both?  My bad if I'm not following

2025-01-25 03:53 UTC, jenniferholm commented on main/FatesHistoryInterfaceMod.F90
> +            long='grazing by herbivores of leaves in kg carbon per m2 per second',          &
This is great to have this FATES_GRAZING output and know the mass of leaves eaten.  In the future could we also have a FATES_GRAZING_LITTER_OUT type output, that gives us an idea of the amount of manure output. Or helps to differentiate how much litter is natural from turnover vs. litter from herbivores.  And maybe useful later for CH4 tracking?

2025-01-25 03:53 UTC, jenniferholm commented on parameter_files/fates_params_default.cdl
> + fates_landuse_grazing_phosphorus_use_eff = 0.5 ;
Are these _use_eff values just placeholders, or from literature (Sam's paper)?  Why again is the carbon_use_eff = 0 ?

2025-01-25 03:53 UTC, jenniferholm commented on parteh/PRTLossFluxesMod.F90
> +    ! will decide what to do with the consumed mass (i.e. sent it to the litter
Just for clarity and ease of understanding, maybe explicitly say where the “grazing-model” is for tracking and clarity. Is this “subroutine FatesGrazing” you mean or something else?

2025-01-27 20:01 UTC, ckoven reviewed
Thanks @jenniferholm for these questions. Tried to update the documentation to capture these points.

2025-01-27 20:01 UTC, ckoven commented on parteh/PRTLossFluxesMod.F90
> +    ! pool or send to atmosphere)
```suggestion
    ! This subroutine assumes that there is no re-translocation associated
    ! with herbivory. There are two pathways for grazed matter. Some fraction 
    ! is lost from the land system (i.e. to the atmosphere via respiration or gas-phase 
    ! nutrient loss pathways), and some fraction is passed to litter decomposition 
    ! (i.e. via manure or grazer mortality). These pathways of consumed biomass 
    ! are handled outside PARTEH (e.g., the litter flux is handled in EDPhysiologyMod, 
    ! and controlled by element-specific "use efficiency" parameters).
```

2025-01-30 00:50 UTC, glemieux commented
> Preliminary regression testing against `sci.1.80.6_api.37.0.0-ctsm5.3.018` baseline shows expected FIELDLIST differences due to the new `FATES_GRAZING` history output not being available in the baselines. Almost all other tests are B4B, with the exception of the `FatesColdPRT2` test:

Rerunning the full `fates` regression tests results in all passing now.  Note that these were not tested against a baseline as these are intended as preliminary.

2025-02-17 23:15 UTC, glemieux commented on parameter_files/archive/api37.0.0_011025_patch_params.xml
> +    </mod>
@ckoven we should add a fates grazing test that checks non-zero grazing rates at some point in the near future.  Can you recommend some  parameter values for the testing?

2025-02-18 21:45 UTC, glemieux approved these changes

2025-02-18 21:47 UTC, glemieux commented
Final regression testing last week is returning B4B results as expected against `fates-sci.1.80.14_api.37.0.0-ctsm5.3.024`.  Only differences showing are due to the default parameter update and `FIELDLIST` differences for the new grazing output added.

2025-02-18 22:48 UTC, merged