Adding day length factor switch
NGEET/fates pull request #1161
Opened 2024-02-14 05:42 UTC by jenniferholm

Adding in a user switch in the parameter file that turns day length factor on (1) by default, or off (2) 

### Description:
This pull request is adding in a user specified switch to turn on or off the day length scaling factor, that is applied to the photosynthetic parameters Vcmax25 and jmax25, and also in the Atkins Maintenance Respiration. This is to be able to allow backwards compatibility with previous versions of the calibration branch.
The function daylength is a scaling factor that is based on the formulation in Bauerle et al. (2012), which quantifies the relationship between day length and Jmax.

### Collaborators:
Greg Lemieux

### Expectation of Answer Changes:
The default is to have the day length factor turned on (equal to 1 in the parameter file), and should have the same results as the most recent calibration branch found here (https://github.com/rgknox/fates/tree/unsupported_sp_calibration_api31)

If turned off, this will change values related to photosynthesis, GPP, and downstream results.

### Checklist

*If this is your first time contributing, please read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/main/CONTRIBUTING.md) document.*

All checklist items must be checked to enable merging this pull request:

*Contributor*
- [ x] The in-code documentation has been updated with descriptive comments
- [ x] The documentation has been assessed to determine if updates are necessary

*Integrator*
- [ ] FATES PASS/FAIL regression tests were run
- [ ] Evaluation of test results for answer changes was performed and results provided

### Documentation

- [Technical Note](https://github.com/NGEET/fates-docs) update:
- [User's Guide](https://github.com/NGEET/fates-users-guide) update: 

### Test Results:

*E3SM test hash-tag:*  a7f4ecb9dd

*E3SM baseline hash-tag:*  a7f4ecb9dd

*FATES baseline hash-tag:* 42d804b
*Test Output:*

2024-03-13 23:21 UTC, glemieux requested changes
Thanks for getting this in @jenniferholm.  I have one clarifying question that may require a code update.

2024-03-21 18:23 UTC, glemieux commented on biogeophys/FatesPlantRespPhotosynthMod.F90
> +    real(r8), intent(in)  :: dayl_factor  ! daylength scaling factor (0-1)
Reviewing this with @rgknox, we're pretty sure this has been superseded and is out of date.

2024-03-21 20:13 UTC, glemieux commented
Regression testing on derecho is underway.

2024-03-21 20:14 UTC, glemieux approved these changes

2024-03-22 17:53 UTC, glemieux commented
Regression testing with the daylength switch turned off (set to `0`) against the baseline `fates-sci.1.72.3_api.34.0.0-ctsm5.1.dev174-default_allom` create using the new default allometry parameters from #1093, shows all expected tests pass b4b.

Testing with the switch on is in progress.

2024-03-22 22:30 UTC, glemieux commented
Regression testing with the switch on results in DIFFs across all fates test mods as expected.  The first timestep appears to be affecting photosynthesis and gpp outputs.

This is ready to integrate after #1128

2024-03-26 00:19 UTC, jenniferholm commented on biogeophys/FatesPlantRespPhotosynthMod.F90
> +    real(r8), intent(in)  :: dayl_factor  ! daylength scaling factor (0-1)
@glemieux - correct, we checked with Jessie today and the dayl_factor should not have been included in the Atkin respiration subroutine, and this was put in here by accident.  I also double checked the Atkins paper, and it's not included.  Not sure why this originally got in?

2024-03-26 02:35 UTC, glemieux commented on biogeophys/FatesPlantRespPhotosynthMod.F90
> +    real(r8), intent(in)  :: dayl_factor  ! daylength scaling factor (0-1)
Thanks for confirming @jenniferholm

2024-04-11 17:35 UTC, jenniferholm commented
Are there checks left to do on this PR?  Jing needs this update in for her simulations, as do I for some updated CNP runs I'm trying to start.  Maybe others do to for the global calibration? Let me know if there is anything I can do to help review.  Thanks!

2024-04-11 17:57 UTC, glemieux commented
@jenniferholm nope, this is all good aside from testing.  It's in the queue and we should be able to integrate it by next week.

2024-04-26 10:53 UTC, rosiealice commented
Just noting that I need to also use this for the calibration work (to allow running with both daylength and Jessie's updates to the vertical respiration scaling)

2024-04-26 12:30 UTC, rgknox commented
testing now

2024-04-26 15:18 UTC, merged

2024-04-26 19:56 UTC, rosiealice commented
Thanks @rgknox :)