Don't zero out `patch%fuel%frac_burnt()` before we use it
NGEET/fates pull request #1302
Opened 2024-12-11 17:01 UTC by adrifoster

Fixes #1301 by checking inside the `TransLitterNewPatch` for the type of disturbance instead of zero-ing outside of the subroutine. 

### Description:

Removed the lines in `spawn_patches` that zero-d the `frac_burnt` array too soon.
Added checks in `TransLitterNewPatch` to check for fire disturbance and a fire on the patch:
   If no fire, new local variable `frac_burnt` set to 0.0, otherwise use `patch%fuel%frac_burnt`

### Collaborators:
@glemieux 

### Expectation of Answer Changes:
Yes - should change answers because before we weren't burning any fuel

### Checklist

*Contributor*
- [x] The in-code documentation has been updated with descriptive comments
- [x] The documentation has been assessed to determine if updates are necessary

*Integrator*
- [ ] FATES PASS/FAIL regression tests were run
- [ ] Evaluation of test results for answer changes was performed and results provided

### Test Results:

*CTSM (or) E3SM (specify which) test hash-tag:* `ctsm5.3.012`

*CTSM (or) E3SM (specify which) baseline hash-tag:* `ctsm5.3.012`

*FATES baseline hash-tag:* `sci.1.80.4_api.37.0.0`

*Test Output:*

Running tests now

2024-12-11 19:02 UTC, glemieux requested changes
I like moving the check into `TransLitterNewPatch`.  That said, do we need to make sure that `currentPatch%fuel%frac_burnt` is set to zero at the end of `spawn_patches` or is that already handled elsewhere?

2024-12-11 20:53 UTC, adrifoster commented
> I like moving the check into `TransLitterNewPatch`. That said, do we need to make sure that `currentPatch%fuel%frac_burnt` is set to zero at the end of `spawn_patches` or is that already handled elsewhere?

I added it to the top of the `fire_model` subroutine, where we zero other fire-related things. I don't know if this is the right place for it or not...

2024-12-16 22:46 UTC, glemieux approved these changes

2025-01-03 18:41 UTC, glemieux commented
Regression testing on `derecho` underway.

2025-01-03 20:20 UTC, glemieux commented
Regression testing agsinst `fates-sci.1.80.5_api.37.0.0-tmp-241219.n01.ctsm5.3.016` is showing DIFFs in the following tests:
```
FAIL ERS_Ld397.f10_f10_mg37.I2000Clm50Fates.derecho_gnu.clm-FatesCold BASELINE fates-sci.1.80.5_api.37.0.0-tmp-241219.n01.ctsm5.3.016: DIFFFAIL ERS_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-FatesColdNoComp BASELINE fates-sci.1.80.5_api.37.0.0-tmp-241219.n01.ctsm5.3.016: DIFFFAIL ERS_Ld397.f45_f45_mg37.I2000Clm50Fates.derecho_intel.clm-FatesColdNoComp BASELINE fates-sci.1.80.5_api.37.0.0-tmp-241219.n01.ctsm5.3.016: DIFF
FAIL SMS_Lm6.f45_f45_mg37.I2000Clm50FatesCruRsGs.derecho_intel.clm-Fates BASELINE fates-sci.1.80.5_api.37.0.0-tmp-241219.n01.ctsm5.3.016: DIFF
```

Spot checking the DIFFs, I think these make sense.  @adrifoster would you take a look when you have a chance to confirm please?

Results: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_pr1302`

2025-01-03 20:48 UTC, adrifoster commented
@glemieux thanks!

yep these look right to me, just to plot some differences:
here are the differences in fire_closs (the new version is higher because now we are actually burning dead fuel):

![ERS_Ld397 f10_f10_mg37 I2000Clm50Fates derecho_gnu clm-FatesCold_FATES_FIRE_CLOSS_mean](https://github.com/user-attachments/assets/fe0e88f9-76d0-4c37-8790-557dd219a498)

which does affect ROS and fire intensity:

![ERS_Ld397 f10_f10_mg37 I2000Clm50Fates derecho_gnu clm-FatesCold_FATES_ROS_mean](https://github.com/user-attachments/assets/da8217c8-576e-4562-9fda-672364a8c6fd)

![ERS_Ld397 f10_f10_mg37 I2000Clm50Fates derecho_gnu clm-FatesCold_FATES_FIRE_INTENSITY_mean](https://github.com/user-attachments/assets/aa6fd7b4-8da4-421b-963f-96f2e4aac3f8)


the new version is **lower** because fuel is actually lower:

![ERS_Ld397 f10_f10_mg37 I2000Clm50Fates derecho_gnu clm-FatesCold_FATES_FUEL_AMOUNT_mean](https://github.com/user-attachments/assets/5074c399-ce6a-4d95-8270-e6d6b7090edd)

2025-01-03 22:51 UTC, glemieux commented
Thanks @adrifoster!

2025-01-03 22:51 UTC, merged