Crown damage module
NGEET/fates pull request #788
Opened 2021-10-01 20:36 UTC by JessicaNeedham

### Description:
This set of changes introduces a crown damage module into FATES. This reduces the crown area and biomass of tissues in the crown -leaves, sapwood, structure, storage and reproductive tissues. Damage can affect canopy or understory cohorts (or both) using the switches hlm_use_canopy_damage and hlm_use_understory_damage. Cohorts are split into damage classes, the number of which is set via the parameter ncrowndamage. The parameter damage_frac sets the fraction of each cohort that gets damaged in each damage event (currently hard coded to be once per year - but working on making this more flexible). The fates_damage_recovery_scalar parameter sets the degree of recovery i.e. allocation to regrow the crown versus staying on damaged allometric trajectory. Two optional parameters can be used to introduce damage-dependent mortality, which captures mortality from damage via mechanisms not represented in FATES. With default parameterisation this would be off. 

### Collaborators:
@ckoven @glemieux @rgknox 

### Expectation of Answer Changes:
With the hlm_use_canopy_damage and hlm_use_understory_damage off runs should be bit for bit with master. Currently that is not the case and I'm looking into why. 
With these switches on then answers will not be bit for bit with master. There will be more cohorts as damage and recovery involve splitting cohorts into damage classes. Damaged cohorts will have smaller canopies which affects AGB and canopy dynamics. Depending on parameterisation carbon starvation mortality may increase. 

### Checklist:

- [ x] My change requires a change to the documentation.
- [ ] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [x ] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

2021-10-04 22:07 UTC, ckoven reviewed
@JessicaNeedham this is really great, thanks!  I have some comments/questions, mostly just to improve clarity.

2021-12-15 15:55 UTC, JessicaNeedham commented on main/FatesHistoryInterfaceMod.F90
> +    ! CROWN DAMAGE VARIABLES
I'm deleting some of the history variables that aren't necessary. Some variables are also output along multiple combinations of dimensions. I could output each variable by just size x pft x damage class and let people aggregate in post processing?

2021-12-16 11:08 UTC, JessicaNeedham commented on main/EDTypesMod.F90
> +  integer,  public :: maxCohortsPerPatch = 300            ! maximum number of cohorts per patch
Agreed, I've updated this.

2021-12-16 11:38 UTC, JessicaNeedham commented on main/FatesHistoryInterfaceMod.F90
> +                       if(hlm_use_canopy_damage .eq. itrue .or. hlm_use_understory_damage .eq. itrue) then
This block needs to be inside the 'if canopy' block.

2021-12-16 11:54 UTC, JessicaNeedham commented on parameter_files/fates_params_default.cdl
> +                fates_damage_frac:long_name = "fraction of cohort damaged in each damage event";
The timing of damage events is specified in DamageMainMod in the is_it_damage_time subroutine (modelled off the is_it_logging_time subroutine). At the moment there is one damage event per year on Jan 1st but users should be able to set specific dates or frequencies. I've updated this comment.

2022-01-10 19:55 UTC, JessicaNeedham commented on main/FatesHistoryInterfaceMod.F90
> +    call this%set_history_var(vname='MORTALITY_CROWNAREA_CANOPY', units = 'm2/ha/year',               &
Updated names and units.

2022-02-28 22:30 UTC, JessicaNeedham commented on main/EDTypesMod.F90
> +     real(r8) :: branch_frac                             ! Fraction of aboveground biomass in branches
I've simplified the code so that branch_frac is no longer a cohort variable. Also updated comments where it is declared.

2022-10-24 18:00 UTC, glemieux requested changes
Initial review due to regression test failure in debug mode.  One other minor suggestion as well.

2022-10-24 18:08 UTC, JessicaNeedham commented on main/FatesParameterDerivedMod.F90
> +        write(fates_log(),'(a/,5(F12.6,1x))') 'annual transition matrix : ', this%damage_transitions(:,:,ft)
Oh, good catch, I agree with putting it in a debug  statement. Or we can delete it. It is supposed to write out the damage transition matrix but I couldn't get  it to work with a variable number of damage bins.

2022-10-24 18:10 UTC, JessicaNeedham commented on biogeophys/FatesPlantRespPhotosynthMod.F90
> +                      end if
Looks good to me.

2022-10-25 16:34 UTC, glemieux commented
Regression testing on Cheyenne is complete.  All expected tests pass b4b.  Note that the tree damage test mod which wasn't generating baselines prior to this PR is now running and generating baselines successfully.  Also, the addition of `MORTALITY_CROWNAREA_CANOPY` and `MORTALITY_CROWNAREA_UNDERSTORY` is resulting in expected `FIELDLIST` DIFFs for those test mods that includes all active history output.

Folder location: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_pr788-crowndamage-2`

2022-10-25 16:36 UTC, glemieux approved these changes

2022-10-31 20:59 UTC, merged